language: python

python:
  - "3.6"

install:
  - pip install flake8
  - pip install -r requirements.txt
  - npm install -g serverless
  - sls plugin install --name serverless-python-requirements

script:
  - flake8 . --max-line-length=120

deploy:
    provider: script
    script: sh deploy.sh
    skip_cleanup: true
    on:
      branch: master
