# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Reply on Mastodon

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download phrases
      run: curl --output phrases.txt $NAGATO_PHRASES_URL
      env:
        NAGATO_PHRASES_URL: ${{ secrets.NAGATO_PHRASES_URL }}
    - name: Reply
      run: python handler.py reply
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        MASTODON_API_BASE_URL: ${{ secrets.MASTODON_API_BASE_URL }}
        NAGATO_LOG_STREAM: 1
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        YAHOO_APPLICATION_ID: ${{ secrets.YAHOO_APPLICATION_ID }}
