name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download phrases.txt
      run: curl --output phrases.txt $NAGATO_PHRASES_URL
      env:
        NAGATO_PHRASES_URL: ${{ secrets.NAGATO_PHRASES_URL }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install serverless-python-requirements
      uses: serverless/github-action@master
      with:
        args: plugin install --name serverless-python-requirements
    - name: serverless deploy
      uses: jackdcasey/github-action@python3.8-nodejs13
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

